/*
 *   Copyright (c) 2025 
 *   All rights reserved.
 */
import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';
export const sample_foods: Food[] = [
    {
      id: '1',
      name: 'Pizza Pepperoni',
      cookTime: '15-20',
      price: 10,
      favorite: false,
      origins: ['italy', 'usa'],
      stars: 4.5,
      imageUrl: 'assets/pizza-pepperoni.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id: '2',
      name: 'Meatball Sub',
      price: 12,
      cookTime: '20-30',
      favorite: true,
      origins: ['usa', 'italy'],
      stars: 4.7,
      imageUrl: 'assets/meatball-sub.jpg',
      tags: ['Sandwich', 'Lunch', 'Dinner'],
    },
    {
      id: '3',
      name: 'Classic Hamburger',
      price: 8,
      cookTime: '10-15',
      favorite: false,
      origins: ['germany', 'usa'],
      stars: 3.9,
      imageUrl: 'assets/classic-hamburger.jpg',
      tags: ['FastFood', 'Burger', 'Dinner'],
    },
    {
      id: '4',
      name: 'Crispy Fries',
      price: 4,
      cookTime: '10-15',
      favorite: true,
      origins: ['belgium', 'france'],
      stars: 4.2,
      imageUrl: 'assets/crispy-fries.jpg',
      tags: ['FastFood', 'Sides', 'Snack'],
    },
    {
      id: '5',
      name: 'Tomato Soup',
      price: 7,
      cookTime: '30-40',
      favorite: false,
      origins: ['italy', 'europe'],
      stars: 3.8,
      imageUrl: 'assets/tomato-soup.jpg',
      tags: ['Vegetarian', 'Soup', 'Lunch'],
    },
    {
      id: '6',
      name: 'Vegetable Pizza',
      price: 11,
      cookTime: '20-25',
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'assets/vegetable-pizza.jpg',
      tags: ['Vegetarian', 'Pizza', 'Lunch', 'Dinner'],
    },
    {
      id: '7',
      name: 'Chicken Shawarma',
      price: 9,
      cookTime: '15-20',
      favorite: true,
      origins: ['middle east'],
      stars: 4.8,
      imageUrl: 'assets/chicken-shawarma.jpg',
      tags: ['FastFood', 'Chicken', 'Dinner'],
    },
    {
      id: '8',
      name: 'Sushi Platter',
      price: 25,
      cookTime: '25-35',
      favorite: true,
      origins: ['japan'],
      stars: 4.9,
      imageUrl: 'assets/sushi-platter.jpg',
      tags: ['Seafood', 'Japanese', 'Dinner'],
    },
    {
      id: '9',
      name: 'Caesar Salad',
      price: 8,
      cookTime: '10-15',
      favorite: false,
      origins: ['mexico', 'usa'],
      stars: 3.7,
      imageUrl: 'assets/caesar-salad.jpg',
      tags: ['Salad', 'Healthy', 'Lunch'],
    },
    {
      id: '10',
      name: 'Beef Stir-Fry',
      price: 16,
      cookTime: '20-25',
      favorite: true,
      origins: ['china', 'asia'],
      stars: 4.6,
      imageUrl: 'assets/beef-stir-fry.jpg',
      tags: ['Asian', 'Dinner', 'Healthy'],
    },
    {
      id: '11',
      name: 'Spaghetti Bolognese',
      price: 14,
      cookTime: '30-45',
      favorite: false,
      origins: ['italy'],
      stars: 4.3,
      imageUrl: 'assets/spaghetti-bolognese.jpg',
      tags: ['Pasta', 'Italian', 'Dinner'],
    },
    {
      id: '12',
      name: 'Taco Kit',
      price: 13,
      cookTime: '20-30',
      favorite: true,
      origins: ['mexico'],
      stars: 4.4,
      imageUrl: 'assets/taco-kit.jpg',
      tags: ['Mexican', 'Dinner', 'FastFood'],
    },
    {
      id: '13',
      name: 'Fish and Chips',
      price: 15,
      cookTime: '20-25',
      favorite: false,
      origins: ['uk'],
      stars: 4.1,
      imageUrl: 'assets/fish-and-chips.jpg',
      tags: ['Seafood', 'FastFood', 'Dinner'],
    },
    {
      id: '14',
      name: 'Pad Thai',
      price: 14,
      cookTime: '25-35',
      favorite: true,
      origins: ['thailand'],
      stars: 4.7,
      imageUrl: 'assets/pad-thai.jpg',
      tags: ['Asian', 'Noodle', 'Dinner'],
    },
    {
      id: '15',
      name: 'Chicken Wings',
      price: 10,
      cookTime: '20-25',
      favorite: false,
      origins: ['usa'],
      stars: 4.0,
      imageUrl: 'assets/chicken-wings.jpg',
      tags: ['FastFood', 'Snack', 'Appetizer'],
    },
    {
      id: '16',
      name: 'Mushroom Risotto',
      price: 18,
      cookTime: '35-45',
      favorite: true,
      origins: ['italy'],
      stars: 4.6,
      imageUrl: 'assets/mushroom-risotto.jpg',
      tags: ['Vegetarian', 'Italian', 'Dinner'],
    },
    {
      id: '17',
      name: 'Doner Kebab',
      price: 9,
      cookTime: '10-15',
      favorite: false,
      origins: ['turkey'],
      stars: 4.3,
      imageUrl: 'assets/doner-kebab.jpg',
      tags: ['FastFood', 'Meat', 'Dinner'],
    },
    {
      id: '18',
      name: 'Chicken Tikka Masala',
      price: 17,
      cookTime: '30-40',
      favorite: true,
      origins: ['india', 'uk'],
      stars: 4.8,
      imageUrl: 'assets/chicken-tikka-masala.jpg',
      tags: ['Indian', 'Spicy', 'Dinner'],
    },
    {
      id: '19',
      name: 'Falafel Wrap',
      price: 7,
      cookTime: '10-15',
      favorite: false,
      origins: ['middle east'],
      stars: 4.1,
      imageUrl: 'assets/falafel-wrap.jpg',
      tags: ['Vegetarian', 'FastFood', 'Lunch'],
    },
    {
      id: '20',
      name: 'Ramen Noodle Soup',
      price: 13,
      cookTime: '20-30',
      favorite: true,
      origins: ['japan'],
      stars: 4.5,
      imageUrl: 'assets/ramen-noodle-soup.jpg',
      tags: ['Japanese', 'Soup', 'Noodle'],
    },
    {
      id: '21',
      name: 'Greek Salad',
      price: 9,
      cookTime: '10-15',
      favorite: false,
      origins: ['greece'],
      stars: 4.0,
      imageUrl: 'assets/greek-salad.jpg',
      tags: ['Vegetarian', 'Salad', 'Healthy'],
    },
    {
      id: '22',
      name: 'Lasagna',
      price: 16,
      cookTime: '45-60',
      favorite: true,
      origins: ['italy'],
      stars: 4.6,
      imageUrl: 'assets/lasagna.jpg',
      tags: ['Pasta', 'Italian', 'Dinner'],
    },
    {
      id: '23',
      name: 'Spring Rolls',
      price: 6,
      cookTime: '10-15',
      favorite: false,
      origins: ['china', 'vietnam'],
      stars: 3.7,
      imageUrl: 'assets/spring-rolls.jpg',
      tags: ['Appetizer', 'Asian', 'Snack'],
    },
    {
      id: '24',
      name: 'Couscous with Vegetables',
      price: 12,
      cookTime: '30-40',
      favorite: true,
      origins: ['north africa'],
      stars: 4.2,
      imageUrl: 'assets/couscous-with-vegetables.jpg',
      tags: ['Vegetarian', 'African', 'Dinner'],
    },
    {
      id: '25',
      name: 'Shrimp Scampi',
      price: 19,
      cookTime: '15-20',
      favorite: false,
      origins: ['italy', 'usa'],
      stars: 4.4,
      imageUrl: 'assets/shrimp-scampi.jpg',
      tags: ['Seafood', 'Pasta', 'Dinner'],
    },
    {
      id: '26',
      name: 'Pancakes with Syrup',
      price: 8,
      cookTime: '10-15',
      favorite: false,
      origins: ['usa', 'canada'],
      stars: 4.0,
      imageUrl: 'assets/pancakes-with-syrup.jpg',
      tags: ['Breakfast', 'Sweet'],
    },
    {
      id: '27',
      name: 'Club Sandwich',
      price: 10,
      cookTime: '10-15',
      favorite: true,
      origins: ['usa'],
      stars: 4.3,
      imageUrl: 'assets/club-sandwich.jpg',
      tags: ['Sandwich', 'Lunch'],
    },
    {
      id: '28',
      name: 'Mango Lassi',
      price: 5,
      cookTime: '5-10',
      favorite: false,
      origins: ['india'],
      stars: 4.5,
      imageUrl: 'assets/mango-lassi.jpg',
      tags: ['Drink', 'Indian', 'Sweet'],
    },
    {
      id: '29',
      name: 'Beef Tacos',
      price: 11,
      cookTime: '15-20',
      favorite: true,
      origins: ['mexico'],
      stars: 4.6,
      imageUrl: 'assets/beef-tacos.jpg',
      tags: ['Mexican', 'FastFood', 'Dinner'],
    },
    {
      id: '30',
      name: 'Croissant',
      price: 3,
      cookTime: '5-10',
      favorite: false,
      origins: ['france'],
      stars: 3.5,
      imageUrl: 'assets/croissant.jpg',
      tags: ['Breakfast', 'Pastry'],
    },
    {
      id: '31',
      name: 'Goulash',
      price: 15,
      cookTime: '45-60',
      favorite: true,
      origins: ['hungary'],
      stars: 4.2,
      imageUrl: 'assets/goulash.jpg',
      tags: ['Stew', 'European', 'Dinner'],
    },
    {
      id: '32',
      name: 'California Sushi Rolls',
      price: 18,
      cookTime: '20-25',
      favorite: false,
      origins: ['japan', 'usa'],
      stars: 4.7,
      imageUrl: 'assets/california-sushi-rolls.jpg',
      tags: ['Seafood', 'Japanese', 'Lunch'],
    },
    {
      id: '33',
      name: 'Hummus Plate',
      price: 7,
      cookTime: '5-10',
      favorite: true,
      origins: ['middle east'],
      stars: 4.5,
      imageUrl: 'assets/hummus-plate.jpg',
      tags: ['Vegetarian', 'Mezze', 'Snack'],
    },
    {
      id: '34',
      name: 'Philly Cheesesteak',
      price: 14,
      cookTime: '15-20',
      favorite: false,
      origins: ['usa'],
      stars: 4.1,
      imageUrl: 'assets/philly-cheesesteak.jpg',
      tags: ['Sandwich', 'FastFood', 'Dinner'],
    },
    {
      id: '35',
      name: 'Lentil Soup',
      price: 6,
      cookTime: '30-40',
      favorite: true,
      origins: ['middle east', 'mediterranean'],
      stars: 4.3,
      imageUrl: 'assets/lentil-soup.jpg',
      tags: ['Vegetarian', 'Soup', 'Healthy'],
    },
    {
      id: '36',
      name: 'Chicken Curry',
      price: 16,
      cookTime: '35-45',
      favorite: false,
      origins: ['india'],
      stars: 4.6,
      imageUrl: 'assets/chicken-curry.jpg',
      tags: ['Indian', 'Spicy', 'Dinner'],
    },
    {
      id: '37',
      name: 'Chocolate Cake',
      price: 7,
      cookTime: '20-30',
      favorite: true,
      origins: ['europe'],
      stars: 4.8,
      imageUrl: 'assets/chocolate-cake.jpg',
      tags: ['Dessert', 'Sweet'],
    },
    {
      id: '38',
      name: 'Green Salad',
      price: 6,
      cookTime: '5-10',
      favorite: false,
      origins: ['global'],
      stars: 3.9,
      imageUrl: 'assets/green-salad.jpg',
      tags: ['Vegetarian', 'Salad', 'Healthy'],
    },
    {
      id: '39',
      name: 'Fish Tacos',
      price: 13,
      cookTime: '15-20',
      favorite: true,
      origins: ['mexico', 'coastal'],
      stars: 4.4,
      imageUrl: 'assets/fish-tacos.jpg',
      tags: ['Seafood', 'Mexican', 'Lunch'],
    },
    {
      id: '40',
      name: 'French Onion Soup',
      price: 8,
      cookTime: '40-50',
      favorite: false,
      origins: ['france'],
      stars: 4.0,
      imageUrl: 'assets/french-onion-soup.jpg',
      tags: ['Soup', 'French', 'ComfortFood'],
    },
  ];

export const sample_tags: Tag[]=[
  {name:"All",count:8},
  {name:"FastFood",count:4},
  {name:"Seafood",count:2},
  {name:"Vegetarian",count:5},
  {name:"Spicy",count:10},
  {name:"Healthy",count:7},
  {name:"Lunch",count:9},
]